<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- <xacro:include filename="inertial_macros.xacro"/> -->


    <xacro:property name="chassis_length" value="0.335" />
    <xacro:property name="chassis_width" value="0.265" />
    <xacro:property name="chassis_height" value="0.138" />
    <xacro:property name="chassis_mass" value="1.0" />
    <xacro:property name="wheel_radius" value="0.033" />
    <xacro:property name="wheel_thickness" value="0.026" />
    <xacro:property name="wheel_mass" value="0.05" />
    <xacro:property name="wheel_offset_x" value="0.226" />
    <xacro:property name="wheel_offset_y" value="0.1485" />
    <xacro:property name="wheel_offset_z" value="0.01" />
    <xacro:property name="caster_wheel_radius" value="0.01" />
    <xacro:property name="caster_wheel_mass" value="0.01" />
    <xacro:property name="caster_wheel_offset_x" value="0.075" />
    <xacro:property name="caster_wheel_offset_z"
        value="${wheel_offset_z - wheel_radius + caster_wheel_radius}" />

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1" />
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1" />
    </material>

    <material name="black">
        <color rgba="0 0 0 1" />
    </material>

    <material name="red">
        <color rgba="1 0 0 1" />
    </material>

    <!-- BASE LINK -->

    <link name="base_link">

    </link>

    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link" />
        <child link="base_footprint" />
        <!-- <origin xyz="0 0 0" rpy="0 0 0"/> -->
        <origin xyz="0 0 -0.11948" rpy="0 0 0" />
        <axis xyz="0.0039682 -0.99999 0" />
    </joint>

    <link name="base_footprint">
        <inertial>
            <origin
                xyz="0.055623 -1.1796E-16 0.046481"
                rpy="0 0 0" />
            <mass
                value="0.33106" />
            <inertia
                ixx="0.00024841"
                ixy="1.9554E-18"
                ixz="2.9769E-05"
                iyy="0.0012783"
                iyz="2.1955E-19"
                izz="0.001084" />
        </inertial>
        <visual>
            <!-- <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/> -->
            <origin xyz="0 0 0" rpy="0 0 0" />
            <!-- <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry> -->
            <geometry>
                <mesh filename="file://$(find halfonso)/meshes/base_footprint.STL" />
            </geometry>
            <!-- <material name="orange"/> -->
            <material
                name="">
                <color rgba="0.49804 0.49804 0.49804 1" />
            </material>
        </visual>

        <!-- <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision> -->

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="file://$(find halfonso)/meshes/base_footprint.STL" />
            </geometry>
        </collision>
        <!-- <xacro:inertial_box mass="0.42011" x="${chassis_length}" y="${chassis_width}"
        z="${chassis_height}">
            <origin xyz="00062538 011608 -0.03299" rpy="0 0 0"/>
        </xacro:inertial_box> -->
    </link>


    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link" />
        <child link="chassis" />
        <origin xyz="0 0 0" />
    </joint>

    <link name="chassis">
        <inertial>
            <origin
                xyz="0.00062538 0.011608 -0.03299"
                rpy="0 0 0" />
            <mass
                value="0.42011" />
            <inertia
                ixx="0.00041367"
                ixy="5.996E-07"
                ixz="5.5589E-05"
                iyy="0.0010659"
                iyz="1.7009E-06"
                izz="0.0012337" />
        </inertial>
        <visual>
            <!-- <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/> -->
            <origin xyz="0 0 0" rpy="0 0 0" />
            <!-- <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry> -->
            <geometry>
                <mesh filename="file://$(find halfonso)/meshes/base_link.STL" />
            </geometry>
            <!-- <material name="orange"/> -->
            <material
                name="">
                <color
                    rgba="0.058824 0.058824 0.058824 1" />
            </material>
        </visual>

        <!-- <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision> -->

        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="file://$(find halfonso)/meshes/base_link.STL" />
            </geometry>
        </collision>
        <!-- <xacro:inertial_box mass="0.42011" x="${chassis_length}" y="${chassis_width}"
        z="${chassis_height}">
            <origin xyz="00062538 011608 -0.03299" rpy="0 0 0"/>
        </xacro:inertial_box> -->
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Orange</material>
    </gazebo>

    <!-- LEFT WHEEL LINK -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel" />
        <!-- <origin xyz="0 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" /> -->
        <origin xyz="-0.071606 0.10612 -0.067079" rpy="1.5708 0 -0.0039682" />
        <axis xyz="0 0 -1" />
    </joint>

    <link name="left_wheel">
        <inertial>
            <origin
                xyz="6.2486E-11 -1.6653E-16 0.011068"
                rpy="0 0 0" />
            <mass
                value="0.049265" />
            <inertia
                ixx="1.07E-05"
                ixy="-6.8378E-22"
                ixz="9.1982E-22"
                iyy="1.07E-05"
                iyz="1.2891E-19"
                izz="1.6785E-05" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <!-- <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/> -->
                <mesh filename="file://$(find halfonso)/meshes/left_wheel.STL" />
            </geometry>
            <!-- <material name="blue"/> -->
            <material name="">
                <color rgba="0.49804 0.49804 0.49804 1" />
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <!-- <sphere radius="${wheel_radius}"/> -->
                <mesh filename="file://$(find halfonso)/meshes/left_wheel.STL" />
            </geometry>
        </collision>
        <!-- <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}"
        radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder> -->
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>


    <!-- RIGHT WHEEL LINK -->

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel" />
        <origin xyz="-0.071606 -0.10612 -0.067079" rpy="-1.5708 0 0.0039682" />
        <axis xyz="0.0079364 0 0.99997" />
    </joint>

    <link name="right_wheel">
        <inertial>
            <origin
                xyz="-2.7756E-17 1.7347E-16 0.011068"
                rpy="0 0 0" />
            <mass
                value="0.049265" />
            <inertia
                ixx="1.07E-05"
                ixy="-6.5289E-22"
                ixz="-1.2672E-21"
                iyy="1.07E-05"
                iyz="-1.2917E-19"
                izz="1.6785E-05" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="file://$(find halfonso)/meshes/right_wheel.STL" />
            </geometry>
            <!-- <material name="blue"/> -->
            <material name="">
                <color rgba="0.49804 0.49804 0.49804 1" />
            </material>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="file://$(find halfonso)/meshes/right_wheel.STL" />
            </geometry>
        </collision>
        <!-- <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}"
        radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder> -->
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>


    <!-- CASTER WHEEL LINK -->

    <!-- <joint name="caster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel"/>
        <origin xyz="${caster_wheel_offset_x} 0 ${caster_wheel_offset_z}"/>
    </joint> -->


    <!-- <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel">
        <material>Gazebo/White</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo> -->

</robot>